create table if not exists public.report
(
    year             integer,
    month            integer,
    day_month_year   integer     not null,
    weekday          varchar(2),
    grid_number      varchar(10) not null,
    dv_arrest        integer,
    dv_investigation integer,
    dv_end_report    integer,
    dv_not_handle    integer,
    tp_arrest        integer,
    tp_investigation integer,
    tp_end_report    integer,
    tp_not_handle    integer,
    sh_arrest        integer,
    sh_investigation integer,
    sh_end_report    integer,
    sh_not_handle    integer,
    ds_arrest        integer,
    ds_investigation integer,
    ds_end_report    integer,
    ds_not_handle    integer,
    da_arrest        integer,
    da_investigation integer,
    da_end_report    integer,
    da_not_handle    integer,
    st_arrest        integer,
    st_investigation integer,
    st_end_report    integer,
    st_not_handle    integer,
    ca_arrest        integer,
    ca_investigation integer,
    ca_end_report    integer,
    ca_not_handle    integer,
    sv_arrest        integer,
    sv_investigation integer,
    sv_end_report    integer,
    sv_not_handle    integer,
    constraint report_pk
        primary key (day_month_year, grid_number)
);

