create table if not exists digitalif.tourist
(
    year             integer,
    month            integer,
    day_month_year   integer    not null,
    weekday          varchar(2),
    grid_number      varchar(6) not null,
    ac_arrest        integer,
    ac_investigation integer,
    ac_end_report    integer,
    ac_not_handle    integer,
    pp_arrest        integer,
    pp_investigation integer,
    pp_end_report    integer,
    pp_not_handle    integer,
    gc_arrest        integer,
    gc_investigation integer,
    gc_end_report    integer,
    gc_not_handle    integer,
    ts_arrest        integer,
    ts_investigation integer,
    ts_end_report    integer,
    ts_not_handle    integer,
    md_arrest        integer,
    md_investigation integer,
    md_end_report    integer,
    md_not_handle    integer,
    name             varchar(30),
    primary key (grid_number, day_month_year)
)